APIDashboard.Web.UI/Models/DashboardIndexViewModel.cs
using APIDashboard.CrossCutting.Models;
using System.Reflection.Metadata.Ecma335;

namespace APIDashboard.Web.UI.Models
{
    public class DashboardIndexViewModel
    {
        public string QuoteContent { get; set; }

        public string QuoteAuthor { get; set; }

        public string APODImg { get; set; }

        public string WeatherLocation { get; set; }

        public float CurrentTemp {get; set;}

        public string WeatherDescription { get; set; }

        public string WeatherIcon { get; set; }



        public DashboardIndexViewModel(Quote quote, APOD apod, CurrentWeather.Rootobject weather)
        {
            QuoteContent = quote.content;
            QuoteAuthor = quote.author;
            APODImg = apod.Hdurl;
            WeatherLocation = weather.name;
            CurrentTemp = weather.main.temp;
            WeatherDescription = weather.weather[0].description;
            WeatherIcon = weather.weather[0].icon;
        }
    }
}

APIDashboard.Web.UI/Controllers/DashboardController.cs
using APIDashboard.CrossCutting.Models;
using APIDashboard.Domain.Orchestrators;
using APIDashboard.Web.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace APIDashboard.Web.UI.Controllers
{
    public class DashboardController : Controller
    {
        private QuoteOrchestrator quoteOrchestrator;
        private APODOrchestrator apodOrchestrator;
        private WeatherOrchestrator weatherOrchestrator;

        public DashboardController()
        {
            quoteOrchestrator = new QuoteOrchestrator();
            apodOrchestrator = new APODOrchestrator();
            weatherOrchestrator = new WeatherOrchestrator();
        }

        public IActionResult Index()
        {
            Quote quote = quoteOrchestrator.GetRandomQuote();
            APOD apod = apodOrchestrator.GetAPOD();
            CurrentWeather.Rootobject weather = weatherOrchestrator.GetCurrentWeather();
            DashboardIndexViewModel viewModel = new DashboardIndexViewModel(quote, apod, weather);
            return View(viewModel);
        }
    }
}

APIDashboard.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace APIDashboard.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

APIDashboard.Web.UI/Views/Dashboard/Index.cshtml
@model APIDashboard.Web.UI.Models.DashboardIndexViewModel

@{
    ViewData["Title"] = "Index";
}


<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <p class="lead">"@Model.QuoteContent"</p>
                <h2 style="text-align: center">@Model.QuoteAuthor</h2>
            </div>
        </div>
    </div>
</section>
<!-- Image element - set the background image for the header in the line below-->
<div class="py-5 bg-image-full" style="background-image: url('@Model.APODImg')">
    <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
    <div style="height: 20rem"></div>
</div>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="">
                <h2>@Model.WeatherLocation</h2>
                <img src='@Model.WeatherIcon' />
                <span>@Model.WeatherDescription</span>
                <p class="mb-0">Current Temperature: @Model.CurrentTemp F</p>
            </div>
        </div>
    </div>
</section>

APIDashboard.Web.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

APIDashboard.Web.UI/Views/Shared/_BootstrapLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Full Width Pics - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Header - set the background image for the header in the line below-->
    <header class="py-5 bg-image-full" style="background-image: url('https://images.unsplash.com/photo-1509226704106-8a5a71ffbfa4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3870&q=80')">
        <div class="text-center my-5">
            <img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="..." />
            <h1 class="text-white fs-3 fw-bolder">Full Width Pics</h1>
            <p class="text-white-50 mb-0">Landing Page Template</p>
        </div>
    </header>
    <!-- Content section-->


    @*<div class="container">
        <main role="main" class="pb-3">*@
            @RenderBody()
       @* </main>
    </div>*@

    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>
</html>

APIDashboard.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APIDashboard.Web.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APIDashboard.Web.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">APIDashboard.Web.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - APIDashboard.Web.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>